spring:
  application:
    name: backend
  cloud:
    consul:
      host: ${CONSUL_URL:0.0.0.0}
      port: 8500
      discovery:
        port: 8080
        prefer-ip-address: true
        healthCheckPath: /health